# Generated by Django 3.1.4 on 2021-05-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('mobile_no', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('roll_no', models.IntegerField()),
            ],
        ),
    ]
